import { useHistory } from '../hooks/useHistory'
import { HistoryRow } from '../components/HistoryRow'
import { historyExportUrl } from '../api/downloadUrl'
import type { Taxonomy } from '../types/taxonomy'
import './HistoryPage.css'

interface HistoryPageProps {
    taxonomy: Taxonomy
    refreshToken: number
}

export function HistoryPage({ taxonomy, refreshToken }: HistoryPageProps) {
    const { records, loading, error, clear } = useHistory(refreshToken)

    return (
        <div className="history-page">
            <div className="history-page__header">
                <div>
                    <h1 className="history-page__title">History</h1>
                    <p className="history-page__subtitle">
                        Every run generated by this backend since it last
                        restarted.
                    </p>
                </div>
                {records && records.length > 0 && (
                    <a href={historyExportUrl()} className="btn btn-ghost">
                        Export all as .zip
                    </a>
                )}
            </div>

            {loading && <p>Loading…</p>}
            {error && <div className="history-page__notice">{error}</div>}

            {records && records.length === 0 && (
                <div className="history-page__empty">
                    No runs yet. Generate one in the Lab to see it here.
                </div>
            )}

            {records && records.length > 0 && (
                <div className="history-page__list">
                    {records.map((record) => (
                        <HistoryRow
                            key={record.id}
                            record={record}
                            taxonomy={taxonomy}
                        />
                    ))}
                </div>
            )}

            {records && records.length > 0 && (
                <button
                    type="button"
                    className="history-page__clear"
                    onClick={clear}
                >
                    Clear history
                </button>
            )}
        </div>
    )
}
